"""add outbox table

The transactional outbox — see app/models/outbox.py for what it is for.

Additive and safe to apply to a running system: a new table, referenced by nothing, with no
foreign keys pointing at it. Rolling back drops it and takes any undelivered messages with it,
which is the honest behaviour — there is nothing else that could be done with them.

Revision ID: 35c27e31465b
Revises: 73d982de7a7a
Create Date: 2026-08-22 13:04:47.754044
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '35c27e31465b'
down_revision: str | None = '73d982de7a7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox')),
    sa.UniqueConstraint('public_id', name=op.f('uq_outbox_public_id'))
    )
    # The worker's whole query, in one index: `WHERE status = 'PENDING' AND available_at <= now()
    # ORDER BY available_at`. Equality column first so Postgres seeks to the PENDING rows, then
    # walks them already sorted — no sort step, and the cost does not grow with the DONE rows
    # piling up behind them.
    #
    # ⚠️ A production version of this is a PARTIAL index — `WHERE status = 'PENDING'` on the index
    # itself — because DONE rows come to outnumber pending ones by orders of magnitude and there
    # is no reason to carry them. Left plain here because it is the shape that transfers to other
    # databases; the partial version is a Postgres speciality worth knowing separately.
    op.create_index('ix_outbox_pending', 'outbox', ['status', 'available_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_pending', table_name='outbox')
    op.drop_table('outbox')
    # ### end Alembic commands ###
